version: '2'

services:
  beta-web:
    image: nginx:${WEB_TAG}
    restart: unless-stopped
    ports:
      - 80:80
      - 7081:7081
      - 7082:7082
      - 7083:7083
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/include/:/etc/nginx/conf.d/
      - ./log/nginx/:/var/log/nginx
      - /html:/html
    links:
      - beta-lzwapi
      - beta-ytzapi
      - beta-zbtapi

  beta-ytzapi:
    image: ytz:${YTZ_TAG}
    restart: unless-stopped
    environment:
      - ENV=${ENV}
    links:
      - beta-sql
      - beta-mongodb
      - beta-redis
      - beta-search

  beta-ytz-worker:
    image: ytz:${YTZ_TAG}
    restart: unless-stopped
    environment:
      - ENV=${ENV}
    links:
      - beta-sql
      - beta-mongodb
      - beta-redis
      - beta-search
    entrypoint:
      - /go/bin/ytz.dforcepro.com
      - worker
      - /go/src/ytz.dforcepro.com/conf/

  # beta-ytz-cron:
  #   image: ytz:${YTZ_TAG}
  #   restart: unless-stopped
  #   environment:
  #     - ENV=${ENV}
  #   links:
  #     - beta-sql
  #     - beta-mongodb
  #     - beta-redis
  #     - beta-search
  #   entrypoint:
  #     - /go/bin/ytz.dforcepro.com
  #     - cron
  #     - /go/src/ytz.dforcepro.com/conf/

  beta-zbtapi:
    image: zbt:${ZBT_TAG}
    restart: unless-stopped
    environment:
      - ENV=${ENV}
    links:
      - beta-mongodb
      - beta-redis
      - beta-search

  beta-zbt-worker:
    image: zbt:${ZBT_TAG}
    restart: unless-stopped
    environment:
      - ENV=${ENV}
    links:
      - beta-mongodb
      - beta-redis
      - beta-search
    entrypoint:
      - /go/bin/zbt.dforcepro.com
      - worker
      - /go/src/zbt.dforcepro.com/conf/

  beta-zbt-cron:
    image: zbt:${ZBT_TAG}
    restart: unless-stopped
    environment:
      - ENV=${ENV}
    links:
      - beta-mongodb
      - beta-redis
      - beta-search
    entrypoint:
      - /go/bin/zbt.dforcepro.com
      - cron
      - /go/src/zbt.dforcepro.com/conf/

  beta-lzwapi:
    image: lzw:${LZW_TAG}
    restart: unless-stopped
    environment:
      - ENV=${ENV}
    volumes:
      - ./data/lzw:/data
    links:
      - beta-mongodb
      - beta-redis

  beta-lzw-cron:
    image: lzw:${LZW_TAG}
    restart: unless-stopped
    environment:
      - ENV=${ENV}
    volumes:
      - ./data/lzw:/data
    links:
      - beta-mongodb
      - beta-redis
    entrypoint:
      - /go/bin/lzw.dforcepro.com
      - cron
      - /go/src/lzw.dforcepro.com/conf/

  beta-mongodb:
      image: mongo:${MONGO_TAG}
      restart: unless-stopped
      environment:
        - MONGO_DATA_DIR=/data/db
        - MONGO_LOG_DIR=/dev/null
      ports:
        - 57001:27017
      volumes:
        - ./mongodb/data:/data/db
      command: mongod --smallfiles --logpath=/dev/null --auth # --quiet

  beta-search:
      image: elasticsearch:${SEARCH_TAG}
      restart: unless-stopped
      volumes:
        - ./elastic/data:/usr/share/elasticsearch/data
      ports:
      - 57003:9200
  
  beta-sql:
    image: mariadb:${SQL_TAG}
    restart: unless-stopped
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_USER=dforcepro
      - MYSQL_PASSWORD=1234
    ports:
      - 57002:3306
    volumes:
      - ./mariadb/data:/var/lib/mysql

  beta-rabbitmq:
    image: rabbitmq:${RABIT_TAG}
    restart: unless-stopped
    hostname: beta-rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=rd
      - RABBITMQ_DEFAULT_PASS=1234

  beta-redis:
    image: redis:${REDIS_TAG}
    restart: unless-stopped

  gorush:
    image: appleboy/gorush:${GORUSH_TAG}
    restart: unless-stopped
    ports: 
      - 8089:8089
    environment: 
      - GORUSH_CORE_PORT=8089
      - GORUSH_CORE_ENABLED=true
      - GORUSH_CORE_MODE=release
      - GORUSH_CORE_SYNC=true
      - GORUSH_ANDROID_APIKEY=${ANDROID_APIKEY}
  pdf:
    image: arachnysdocker/athenapdf-service:${PDF_TAG}
    environment:
      - WEAVER_AUTH_KEY=${PDF_AUTH_KEY}
    ports:
      - 8080:8080
  # beta-prometheus:
  #   image: prom/prometheus:${PROMETHEUS_TAG}
  #   restart: unless-stopped
  #   volumes:
  #     - ./prometheus:/prometheus