apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: ./kompose convert -f docker-compose.yml
    kompose.version: 1.8.0 (0c0c027)
  creationTimestamp: null
  labels:
    io.kompose.service: gorush
  name: gorush
spec:
  ports:
  - name: "8089"
    port: 8089
    targetPort: 8089
  selector:
    io.kompose.service: gorush
status:
  loadBalancer: {}
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: ./kompose convert -f docker-compose.yml
    kompose.version: 1.8.0 (0c0c027)
  creationTimestamp: null
  labels:
    io.kompose.service: gorush
  name: gorush
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: gorush
    spec:
      containers:
      - env:
        - name: GORUSH_ANDROID_APIKEY
          value: "AAAAuKNG3bc:APA91bEDzwTF5vzHfle9ez8UvCcQDek3YopwOFC-aG-1nuLpwfrzIMtO8Msep9vmPKZiIvDt2GS1fv39pMEJlf1FJI8h6kqiV7Ed0OPibvpvraizC13qa8peJX45Jvv3WQw5KhJEVj2q"
        - name: GORUSH_CORE_ENABLED
          value: "true"
        - name: GORUSH_CORE_MODE
          value: release
        - name: GORUSH_CORE_PORT
          value: "8089"
        - name: GORUSH_CORE_SYNC
          value: "true"
        image: 'appleboy/gorush:1.10.0'
        name: gorush
        ports:
        - containerPort: 8089
        resources: {}
      restartPolicy: Always
status: {}