apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: ./kompose convert -f docker-compose.yml
    kompose.version: 1.8.0 (0c0c027)
  creationTimestamp: null
  labels:
    io.kompose.service: beta-mongodb
  name: beta-mongodb
spec:
  externalIPs:
  - 192.168.100.111
  ports:
  - name: "57001"
    port: 57001
    targetPort: 27017
  selector:
    io.kompose.service: beta-mongodb
status:
  loadBalancer: {}
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: ./kompose convert -f docker-compose.yml
    kompose.version: 1.8.0 (0c0c027)
  creationTimestamp: null
  labels:
    io.kompose.service: beta-mongodb
  name: beta-mongodb
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: beta-mongodb
    spec:
      containers:
      - args:
        - mongod
        - --smallfiles
        #- --logpath=/dev/null
        env:
        - name: MONGO_DATA_DIR
          value: /data/
        - name: MONGO_LOG_DIR
          value: /var/log/
        image: 'mongo:3.6.1'
        name: beta-mongodb
        ports:
        - containerPort: 27017
        resources: {}
        volumeMounts:
        - mountPath: /data/db
          name: beta-mongodb-claim0
      restartPolicy: Always
      nodeSelector:
        disktype: nas
      volumes:
      - name: beta-mongodb-claim0
        persistentVolumeClaim:
          claimName: beta-mongodb-claim0
status: {}
