apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: ./kompose convert -f docker-compose.yml
    kompose.version: 1.8.0 (0c0c027)
  creationTimestamp: null
  labels:
    io.kompose.service: pdf
  name: pdf
spec:
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  selector:
    io.kompose.service: pdf
status:
  loadBalancer: {}
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: ./kompose convert -f docker-compose.yml
    kompose.version: 1.8.0 (0c0c027)
  creationTimestamp: null
  labels:
    io.kompose.service: pdf
  name: pdf
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: pdf
    spec:
      containers:
      - env:
        - name: WEAVER_AUTH_KEY
          value: "dforcepro-beta"
        image: 'arachnysdocker/athenapdf-service:2.10.0'
        name: pdf
        ports:
        ports:
        - containerPort: 8080
        resources: {}
      restartPolicy: Always
status: {}
