apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: ./kompose convert -f docker-compose.yml
    kompose.version: 1.8.0 (0c0c027)
  creationTimestamp: null
  labels:
    io.kompose.service: beta-rabbitmq
  name: beta-rabbitmq
spec:
  ports:
  - name: "5672"
    port: 5672
    targetPort: 0
  selector:
    io.kompose.service: beta-rabbitmq
status:
  loadBalancer: {}
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: ./kompose convert -f docker-compose.yml
    kompose.version: 1.8.0 (0c0c027)
  creationTimestamp: null
  labels:
    io.kompose.service: beta-rabbitmq
  name: beta-rabbitmq
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: beta-rabbitmq
    spec:
      containers:
      - env:
        - name: RABBITMQ_DEFAULT_PASS
          value: "1234"
        - name: RABBITMQ_DEFAULT_USER
          value: rd
        image: 'rabbitmq:3.7'
        name: beta-rabbitmq
        ports:
        ports:
        - containerPort: 5672
        resources: {}
      restartPolicy: Always
status: {}
