apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: ./kompose convert -f docker-compose.yml
    kompose.version: 1.8.0 (0c0c027)
  creationTimestamp: null
  labels:
    io.kompose.service: beta-ydtapi
  name: beta-ydtapi
spec:
  ports:
  - name: "9080"
    port: 9080
    targetPort: 9080
  selector:
    io.kompose.service: beta-ydtapi
status:
  loadBalancer: {}
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: ./kompose convert -f docker-compose.yml
    kompose.version: 1.8.0 (0c0c027)
  creationTimestamp: null
  labels:
    io.kompose.service: beta-ydtapi
  name: beta-ydtapi
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: beta-ydtapi
    spec:
      containers:
      - env:
        - name: ydt-1.0.9
        image: '192.168.100.111:5000/ydt-1.0.9'
        name: beta-ydtapi
        ports:
        - containerPort: 9080
        resources: {}
      restartPolicy: Always
status: {}
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: ./kompose convert -f docker-compose.yml
    kompose.version: 1.8.0 (0c0c027)
  creationTimestamp: null
  labels:
    io.kompose.service: beta-ydtadmin
  name: beta-ydtadmin
spec:
  ports:
  - name: "9080"
    port: 9080
    targetPort: 9080
  selector:
    io.kompose.service: beta-ydtadmin
status:
  loadBalancer: {}
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: ./kompose convert -f docker-compose.yml
    kompose.version: 1.8.0 (0c0c027)
  creationTimestamp: null
  labels:
    io.kompose.service: beta-ydtadmin
  name: beta-ydtadmin
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: beta-ydtadmin
    spec:
      containers:
      - command:
        - /go/bin/ydt.admin  
        - api
        - /go/src/ydt.dforcepro.com/conf/
        env:
        - name: ydt-1.0.9
        image: '192.168.100.111:5000/ydt-1.0.9'
        name: beta-ydtadmin
        ports:
        - containerPort: 9080
        resources: {}
      restartPolicy: Always
status: {}
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: ./kompose convert -f docker-compose.yml
    kompose.version: 1.8.0 (0c0c027)
  creationTimestamp: null
  labels:
    io.kompose.service: beta-ydtgateway
  name: beta-ydtgateway
spec:
  ports:
  - name: "9080"
    port: 9080
    targetPort: 9080
  selector:
    io.kompose.service: beta-ydtgateway
status:
  loadBalancer: {}
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: ./kompose convert -f docker-compose.yml
    kompose.version: 1.8.0 (0c0c027)
  creationTimestamp: null
  labels:
    io.kompose.service: beta-ydtgateway
  name: beta-ydtgateway
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: beta-ydtgateway
    spec:
      containers:
      - command:
        - /go/bin/ydt.gateway  
        - api
        - /go/src/ydt.dforcepro.com/conf/
        env:
        - name: ydt-1.0.9
        image: '192.168.100.111:5000/ydt-1.0.9'
        name: beta-ydtgateway
        ports:
        - containerPort: 9080
        resources: {}
      restartPolicy: Always
status: {}