apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: ./kompose convert -f docker-compose.yml
    kompose.version: 1.8.0 (0c0c027)
  creationTimestamp: null
  labels:
    io.kompose.service: beta-ytzapi
  name: beta-ytzapi
spec:
  ports:
  - name: "9080"
    port: 9080
    targetPort: 9080
  selector:
    io.kompose.service: beta-ytzapi
status:
  loadBalancer: {}
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: ./kompose convert -f docker-compose.yml
    kompose.version: 1.8.0 (0c0c027)
  creationTimestamp: null
  labels:
    io.kompose.service: beta-ytz-worker
  name: beta-ytz-worker
spec:
  ports:
  - name: headless
    port: 55555
    targetPort: 0
  selector:
    io.kompose.service: beta-ytz-worker
status:
  loadBalancer: {}
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: ./kompose convert -f docker-compose.yml
    kompose.version: 1.8.0 (0c0c027)
  creationTimestamp: null
  labels:
    io.kompose.service: beta-ytzapi
  name: beta-ytzapi
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: beta-ytzapi
    spec:
      containers:
      - env:
        - name: ytz-1.1.1
        image: '192.168.100.111:5000/ytz-1.1.1'
        name: beta-ytzapi
        ports:
        - containerPort: 9080
        resources: {}
      restartPolicy: Always
status: {}
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: ./kompose convert -f docker-compose.yml
    kompose.version: 1.8.0 (0c0c027)
  creationTimestamp: null
  labels:
    io.kompose.service: beta-ytz-worker
  name: beta-ytz-worker
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: beta-ytz-worker
    spec:
      containers:
      - command:
        - /go/bin/ytz.dforcepro.com
        - worker
        - /go/src/ytz.dforcepro.com/conf/
        env:
        - name: worker_ytz-1.1.1
        image: '192.168.100.111:5000/ytz-1.1.1'
        name: beta-ytz-worker
        resources: {}
      restartPolicy: Always
status: {}
