apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: ./kompose convert -f docker-compose.yml
    kompose.version: 1.8.0 (0c0c027)
  creationTimestamp: null
  labels:
    io.kompose.service: beta-zbtapi
  name: beta-zbtapi
spec:
  ports:
  - name: "9080"
    port: 9080
    targetPort: 9080
  selector:
    io.kompose.service: beta-zbtapi
status:
  loadBalancer: {}
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: ./kompose convert -f docker-compose.yml
    kompose.version: 1.8.0 (0c0c027)
  creationTimestamp: null
  labels:
    io.kompose.service: beta-zbt-worker
  name: beta-zbt-worker
spec:
  ports:
  - name: headless
    port: 55555
    targetPort: 0
  selector:
    io.kompose.service: beta-zbt-worker
status:
  loadBalancer: {}
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: ./kompose convert -f docker-compose.yml
    kompose.version: 1.8.0 (0c0c027)
  creationTimestamp: null
  labels:
    io.kompose.service: beta-zbt-cron
  name: beta-zbt-cron
spec:
  ports:
  - name: headless
    port: 55555
    targetPort: 0
  selector:
    io.kompose.service: beta-zbt-cron
status:
  loadBalancer: {}
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: ./kompose convert -f docker-compose.yml
    kompose.version: 1.8.0 (0c0c027)
  creationTimestamp: null
  labels:
    io.kompose.service: beta-zbtapi
  name: beta-zbtapi
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: beta-zbtapi
    spec:
      containers:
      - env:
        - name: zbt-1.1.2
        image: '192.168.100.111:5000/zbt-1.1.2'
        name: beta-zbtapi
        ports:
        - containerPort: 9080
        resources: {}
      restartPolicy: Always
status: {}
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: ./kompose convert -f docker-compose.yml
    kompose.version: 1.8.0 (0c0c027)
  creationTimestamp: null
  labels:
    io.kompose.service: beta-zbt-worker
  name: beta-zbt-worker
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: beta-zbt-worker
    spec:
      containers:
      - command:
        - /go/bin/zbt.dforcepro.com  
        - worker
        - /go/src/zbt.dforcepro.com/conf/
        env:
        - name: zbt-1.1.2
        image: '192.168.100.111:5000/zbt-1.1.2'
        name: beta-zbt-worker
        resources: {}
      restartPolicy: Always
status: {}
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: ./kompose convert -f docker-compose.yml
    kompose.version: 1.8.0 (0c0c027)
  creationTimestamp: null
  labels:
    io.kompose.service: beta-zbt-cron
  name: beta-zbt-cron
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: beta-zbt-cron
    spec:
      containers:
      - command:
        - /go/bin/zbt.dforcepro.com  
        - cron
        - /go/src/zbt.dforcepro.com/conf/
        env:
        - name: zbt-1.1.2
        image: '192.168.100.111:5000/zbt-1.1.2'
        name: beta-zbt-cron
        resources: {}
      restartPolicy: Always
status: {}