apiVersion: batch/v1
kind: Job
metadata:
  name: ytz-api-letsencrypt-job
  labels:
    app: ytz-api-letsencrypt
spec:
  template:
    metadata:
      name: letsencrypt
      labels:
        app: ytz-api-letsencrypt
    spec:
      containers:
      # Bash script that starts an http server and launches certbot
      # Fork of github.com/sjenning/kube-nginx-letsencrypt 
      - image: sjenning/kube-nginx-letsencrypt:0.8.1-1
        name: letsencrypt
        imagePullPolicy: Always
        ports:
        - name: letsencrypt
          containerPort: 80
        env:
        - name: DOMAINS
          value: beta-api.ytz.dforcepro.com # Domain you want to use. CHANGE ME!
        - name: EMAIL
          value: tig4605246@gmail.com # Your email. CHANGE ME!
        - name: SECRET
          value: api-ytz-letsencrypt-certs
      restartPolicy: Never
---
apiVersion: v1
kind: Service
metadata:
  name: ytz-api-letsencrypt-service
spec:
  selector:
    app: ytz-api-letsencrypt
  ports:
  - protocol: "TCP"
    port: 80