 apiVersion: v1
 data:
   proxy-connect-timeout: "15"
   proxy-read-timeout: "600"
   proxy-send-timeout: "600"
   hsts-include-subdomains: "false"
   body-size: "64m"
   server-name-hash-bucket-size: "256"
   #proxy-body-size: "2m"
   #bind-address-ipv4: "192.168.0.11"
   80: "default/beta-ytzapi:9080"
   57001: "default/beta-mongodb:27017"
 kind: ConfigMap
 metadata:
   namespace: default
   name: nginx